config/routes.rb
Rails.application.routes.draw do
  get 'bookings/index'

  devise_for :users
  root to: "pages#home"
  get 'mybookings', to: "users#bookings"
  get 'mylistings', to: 'users#listings'
  resources :yachts do
    resources :bookings
    resources :reviews
  end

  resources :bookings, only: [] do
    member do
      patch :accept
      patch :reject
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :yacht
  validates :check_in, :check_out, :guests, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :yacht
  belongs_to :user
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :yachts, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews
end

app/models/yacht.rb
class Yacht < ApplicationRecord
  has_many_attached :photos
  has_many :reviews
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  # , uniqueness: true
  validates :amenities, inclusion: { in: (["bathroom", "swimming pool", "wifi", "helipad", "gym", "cinema", "basketball court", "aircon", "heating"]),
                                     message: "%{value} is not a valid amenity" }
  validates :capacity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :location, presence: true
  validates :price_per_night, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_yacht, only: %i[new create update]
  before_action :set_user, only: %i[new create update]
  def index
    @bookings = Booking.all
  end


  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.yacht = @yacht
    @booking.user = @user
    if @booking.save
      redirect_to mybookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(request: true)
    redirect_to mylistings_path
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.update(request: false)
    redirect_to mylistings_path
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to yacht_booking_path(@yacht, @booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to mybookings_path, status: :see_other
  end

  private

  def set_yacht
    @yacht = Yacht.find(params[:yacht_id])
  end

  def set_user
    @user = current_user
  end

  def booking_params
    params.require(:booking).permit(:check_in, :check_out, :guests)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_yacht, only: %i[new create]
  def new
    @review = Review.new
  end

  def create
    @user = current_user
    @review = Review.new(review_params)
    @review.yacht = @yacht
    @review.user = @user
    if @review.save
      redirect_to yacht_path(@yacht)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_yacht
    @yacht = Yacht.find(params[:yacht_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[listings]
  def bookings
    @bookings = current_user.bookings

  end

  def listings


  end

  private

  def set_user
    @user = current_user
  end
end

app/controllers/yachts_controller.rb
class YachtsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @yachts = Yacht.all
    if params[:query].present? && params[:query].to_i == 0
      sql_subquery = "name ILIKE :query OR location ILIKE :query"
      @yachts = @yachts.where(sql_subquery, query: "%#{params[:query]}%")
    elsif params[:query].to_i != 0
      @yachts = @yachts.where(capacity: params[:query].to_i)
    end
  end

  def show
    @yacht = Yacht.find(params[:id])
    @user = current_user
    @booking = Booking.new
    @yacht_arr = Yacht.where(id: params[:id])
    @markers = @yacht_arr.geocoded.map do |yacht|
      {
        lat: yacht.latitude,
        lng: yacht.longitude,
      }
    end
  end

  def new
    @yacht = Yacht.new
  end

  def create
    @user = current_user
    @yacht = Yacht.new(yacht_params)
    @yacht.user = @user
    if @yacht.save
      redirect_to mylistings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @yacht = Yacht.find(params[:id])
  end

  def update
    @yacht = Yacht.find(params[:id])
    @yacht.update(yacht_params)
    if @yacht
      redirect_to yacht_path(@yacht)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @yacht = Yacht.find(params[:id])
    @yacht.destroy
    redirect_to mylistings_path, status: :see_other
  end

  private

  def yacht_params
    params.require(:yacht).permit(:capacity, :price_per_night, :name, :description, :location, :amenities, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>My Bookings</h1>
 <ul>
  <% @bookings.each do |booking| %>
    <li>
    <%= booking.user_id %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YachtAirbnbClonee</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Comfortaa:wght@300&family=Inter:wght@300;400;600&family=Poppins:wght@100;200;300;400&family=Raleway:wght@600;900&family=Roboto&family=Urbanist:wght@200&family=Work+Sans:ital,wght@0,100;0,200;0,300;0,400;0,600;0,700;0,900;1,100;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">

  </head>

  <body>
  <%= render "shared/navbar" %>
  <div style="min-height: 594px;">
  <%= yield %>
  </div>
  <% # nav_bar %>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

     <%= render "shared/footer" %>


  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1523496922380-91d5afba98a3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3264&q=80); ">
  <div class="container" style= "text-align: center;">
    <h1 class="mb-4">Jacht forever</h1>
    <h2>Yacht with us</h2>
<%# Link added to index page %>
    <%= link_to "Book now", yachts_path, class: "btn btn-primary btn-cta"  %>
  </div>

</div>

<div class="container1 m-5 ">
   <h5 style=" margin:60px;text-align: center; line-height: 2;">
      Imagine a world where turquoise waters stretch as far as the eye can see, where the gentle caress of the sea breeze carries your worries away, and where opulent luxury meets unparalleled adventure. Welcome to JachtForever, the premier destination for booking exquisite yachts and embarking on the voyage of a lifetime.
    </h5>


    <div class=" cards_container row flex-container flex-direction: row; ">
      <div class=" column card-category" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1561751788-85fcb8b78413?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3432&q=80); background-size: 100% 100%; color: white; text-align: center; justify-content:center;">
        <h3> Your Journey, Your Way</h3>
      </div>

      <div class=" column card-category" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1527588574470-7152d7c3c15e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjA2fHx5YWNodHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60); background-size: cover; color: white; justify-content: center; align-items: center;">
       <h3>Seamless Booking, Impeccable Service </h3>
      </div>
     </div>


</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid">
  <% if params[:action] == "index" %>
    <%= link_to root_path, class: "navbar-brand" do %>
     <i class="fa-solid fa-sailboat"></i>
     <% end %>
  <% else %>
    <%= link_to yachts_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-sailboat"></i>
    <% end %>
  <% end %>
       <%# <p class="brand_name">Jacht</p> %>



    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa-solid fa-bars"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item dropdown">
          <a class="nav-link avatar dropdown cursor: pointer;" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i style="cursor: pointer;" class="fa-solid fa-user"></i>
          </a>

          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
              <% case params[:action] %>
              <% when "index" %>
                  <%= link_to "My Bookings", mybookings_path, class: "dropdown-item" %>
                  <%= link_to "My Listings", mylistings_path, class: "dropdown-item" %>
                  <%= link_to "Log Out", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } %>
                  <p class="mx-3 mt-2">Logged in as <%= current_user.first_name %></p>
                <% when "bookings" %>
                  <%= link_to "View Yachts", yachts_path, class: "dropdown-item" %>
                  <%= link_to "My Listings", mylistings_path, class: "dropdown-item" %>
                  <%= link_to "Log Out", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } %>
                  <p class="mx-3 mt-2">Logged in as <%= current_user.first_name %></p>
                <% when "listings" %>
                  <%= link_to "View Yachts", yachts_path, class: "dropdown-item" %>
                  <%= link_to "My Bookings", mybookings_path, class: "dropdown-item" %>
                  <%= link_to "Log Out", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } %>
                  <p class="mx-3 mt-2">Logged in as <%= current_user.first_name %></p>
                <% else %>
                  <%= link_to "View Yachts", yachts_path, class: "dropdown-item" %>
                  <%= link_to "My Bookings", mybookings_path, class: "dropdown-item" %>
                  <%= link_to "My Listings", mylistings_path, class: "dropdown-item" %>
                  <%= link_to "Log Out", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } %>
                  <p class="mx-3 mt-2">Logged in as <%= current_user.first_name %></p>
              <% end %>
            <% else %>
              <%= link_to "View Yachts", yachts_path, class: "dropdown-item" %>
              <%= link_to "Log In", new_user_session_path, class: "dropdown-item" %>
              <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
<% # nav_bar_end %>

app/views/users/_nobookings.html.erb
<div class="container py-2">
  <div class="row" id="row">
    <div class="col-md-4 d-flex align-items-center justify-content-center">
      <div class="nobooking">
        <p class="text-center">No booking made yet.</p>
        <%= link_to "Book Now", yachts_path, class: "btn btn-outline-info d-block mx-auto" %>
      </div>
    </div>
    <div class="col-md-8">
      <div style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1561751788-85fcb8b78413?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3432&q=80); background-size: cover; border-bottom-right-radius: 30px; height: 400px;"></div>
    </div>
  </div>
</div>

<style>
p {
  margin: 30px; /* To remove default margin */


}

#row {
  background-color: white;
  border-radius: 30px;
}

/* Additional styles for the container */
.container {
  margin-top: 30px;

}

/* Additional styles for the image div */
.col-md-8  div {
  border-top-right-radius: 30px;
  border-bottom-right-radius: 30px;
  margin: 0;
  padding :0;
}
div{
padding:0;
}
.row > * {
  flex-shrink: 0;
  padding-right: calc(var(--bs-gutter-x) * .0);
  padding-left: calc(var(--bs-gutter-x) * .0);
  margin-top: var(--bs-gutter-y);
}
</style>

app/views/users/bookings.html.erb
<div class="container">
  <div class="text-button-container">
    <h2 class="mt-5">My Bookings</h2>
    <div class='text-center rounded mt-2 mb-2'><%= link_to "Browse Yachts", yachts_path, class: 'btn-small' %></div>
  </div>

<% if @bookings.length.positive? %>
     <%= render partial: 'hasbookings' %>
     <% else %>
     <%= render partial: 'nobookings' %>
   <% end %>
</div>

app/views/users/listings.html.erb
 <div class="container">

<!-- My yachts iteration-->
  <div class="top-text-button">
    <h2 class="pt-5 pb-3">My Yachts</h2>
    <div class="button ">
    <%= link_to "Add a Yacht", new_yacht_path, class: "btn-small" %>
    </div>
  </div>

  <div class="listing-yacht-container">
      <% @user.yachts.each do |yacht| %>
      <div class="listing-yacht-card">
            <div class="listing-yacht-image">
          <% if yacht.photos.attached? %>
                <img src="<%= cl_image_path yacht.photos.first.key %>" alt="yacht-image">
              <% else %>
                <img src="https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8eWFjaHR8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60" alt="yacht-image">
              <% end %>
            </div>
            <div class="listing-yacht-name">
                <h5><%= yacht.name %></h5>
                <p><%= yacht.location %></p>
            </div>
          <div class="links d-flex justify-content-between">
            <p><%= link_to icon('fa-solid', 'pen-to-square', class: 'fa-1x'), edit_yacht_path(yacht) %></p>
            <p><%= link_to icon('fa-solid', 'trash', class: 'fa-1x'),
                yacht_path(yacht),
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
            %></p>
          </div>
          </div>
      <% end %>
   </div>

<!-- My listings iteration-->
    <h2 class="pt-4 pb-3">My Listings</h2>
      <div class="booking-requests-container">
        <% @user.yachts.each do |yacht| %>
              <% yacht.bookings.each do |booking| %>
            <div class="booking-requests-cards" data-controller="requestbuttons">
                  <h6><%= booking.user.email %> has requested:</h6>
                  <h5><strong><%= booking.yacht.name.upcase%></strong></h5>
                  <p><strong>Check-in date: </strong><%= booking.check_in %></p>
                  <p><strong>Check-out date: </strong><%= booking.check_out %></p>
                  <p data-requestbuttons-target="requestText">Request:   <% if booking.request == nil %>
                                  <%= "pending"%>
                                <% elsif booking.request == true %>
                                <%= "accepted"%>
                                <% else %>
                                <%= "rejected"%>
                                <% end %></p>
                  <div class="request-buttons">
                      <% if booking.request == nil %>
                    <div data-action="click->requestbuttons#disable" data-requestbuttons-target="acceptButton" style="margin-right:10px;">
                        <%= button_to "Accept", accept_booking_path(booking), method: :patch, class:"btn btn-outline-success d-block mx-auto" %></div>
                      <div data-action="click->requestbuttons#disable" data-requestbuttons-target="rejectButton" style="margin-right:10px;">
                        <%= button_to "Reject", reject_booking_path(booking), method: :patch, class:"btn btn-outline-danger d-block mx-auto"%></div>
                    <% end %>
                    </div>
          </div>
              <% end %>
           <% end %>
       </div>
</div>

app/views/yachts/index.html.erb
<%# <%= render "shared/navbar" %>
<div class="container my-5">
  <div class="show-nav">
    <div>
      <h2>Yachts</h2>
      <p>Explore our magical yachts</p>
    </div>
         <div class="col-sm-4 my-3">
    <%= form_with url: yachts_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search..."
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-outline-info"%>


    <% end %>
  </div>
  </div>


  <div class="container">
    <div class="yachts_index_container row flex-container flex-direction: row mt-4">
      <% @yachts.each do |yacht| %>
        <div class="yacht-cards">
          <%= link_to yacht_path(yacht) do%>
          <% if yacht.photos.attached? %>
           <div id="carouselExampleIndicators<%= yacht.id %>" class="carousel slide" data-interval="false">
              <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators<%= yacht.id %>" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators<%= yacht.id %>" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators<%= yacht.id %>" data-bs-slide-to="2" aria-label="Slide 3"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators<%= yacht.id %>" data-bs-slide-to="3" aria-label="Slide 4"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators<%= yacht.id %>" data-bs-slide-to="4" aria-label="Slide 5"></button>
              </div>
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="<%= cl_image_path yacht.photos[0].key %>" class="d-block w-100" alt="yacht">
                </div>
                <div class="carousel-item">
                  <img src="<%= cl_image_path yacht.photos[1].key %>" class="d-block w-100" alt="yacht kitchen">
                </div>
                <div class="carousel-item">
                  <img src="<%= cl_image_path yacht.photos[2].key %>" class="d-block w-100" alt="yacht living room">
                </div>
                <div class="carousel-item">
                  <img src="<%= cl_image_path yacht.photos[3].key %>" class="d-block w-100" alt="yacht bedroom">
                </div>
                <div class="carousel-item">
                  <img src="<%= cl_image_path yacht.photos[4].key %>" class="d-block w-100" alt="yacht deck">
                </div>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators<%= yacht.id %>" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators<%= yacht.id %>" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>

          <% else %>
            <img src="https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8eWFjaHR8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60" alt="yacht-image">
          <% end %>
          <div class="top-text">
            <h5 class="ml-0"><%= link_to yacht.name, yacht_path(yacht) %></h5> <!-- Link to show page -->
            <div><i class="fa-solid fa-person"></i><%= yacht.capacity %></div>
          </div>
            <div><%yacht.reviews.each do |review| %>
                  <%= review.rating %> ⭐️
                  <% end %>
            </div>
          <div class="bottom-text">
            <p><%= yacht.location %></p>
            <p>PPN £<%= yacht.price_per_night %>0</p>
          </div>
        <% end %>
        </div>
        <% end %>
    </div>
  </div>
</div>



<!-- Styling notes to do:
  - Nicer button on line 7
  - New images for each iteration
  - Link image?
  - Edit cards w/ media-width >

app/views/yachts/show.html.erb
<div class="container my-5">
   <div class=" d-flex flex-row justify-content-between">
   <div class="name-location-container">
      <h2 class= "mx-3"><%= @yacht.name %></h2>
        <div class="d-flex ">
          <h3 class="mx-3 mt-1 mb-3">Location: <%= @yacht.location %></h3>
        </div>
      </div>
       <div class="mt-3 text-start">
               <%= link_to "Back To All Yachts", yachts_path, class: "btn-small" %>
            </div>
   </div>


   <div>
      <div class="container">
         <div class="row">
            <div class="large-img col-md-6">
               <img src="<%= cl_image_path @yacht.photos[0].key %>" alt="yacht-image" alt="yacht-image" class="img-fluid w-100">
            </div>
            <div class="mini-imgs col-md-6 d-flex flex-row">
               <div class="row">
                  <div class="col-6 new-mini">
                     <img src="<%= cl_image_path @yacht.photos[1].key %>" alt="yacht-image" alt="yacht-image" class="img-fluid img-one">
                     <img src="<%= cl_image_path @yacht.photos[2].key %>" alt="yacht-image" alt="yacht-image" class="img-fluid img-two">
                  </div>
                  <div class="col-6 bottom-img">
                     <img src="<%= cl_image_path @yacht.photos[3].key %>" alt="yacht-image" alt="yacht-image" class="img-fluid img-three">
                     <img src="<%= cl_image_path @yacht.photos[4].key %>" alt="yacht-image" alt="yacht-image" class="img-fluid img-four">
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <div class="d-flex mt-4 justify-content-between">
      <div class="yacht-detial-container text-center" style="margin: 10px;">
         <div class="text-start">
            <h5>
            Yatch hosted by <%= @yacht.user.first_name %> <%= @yacht.user.last_name %></h6>
         </div>
         <br>
         <div class="yacht-detail-cards">
            <div class="col-md-3">
            <div class="yacht-detail-card pl-4 ">
               <% # <div class="yacht-detail-card-content"> %>
               <i class="fa-solid fa-person"></i>
               <% # </div> %>
               <% # <div class="yacht-detail-card-content"> %>
               <p><%= @yacht.capacity %></p>
               <% # </div> %>
            </div>
            <div class="yacht-detail-card ">
               <% # <div class="yacht-detail-card-content"> %>
               <i class="fa-solid fa-helicopter"></i>
               <% # </div> %>
               <% # <div class="yacht-detail-card-content"> %>
               <p><%= @yacht.amenities.capitalize %></p>
               <% # </div> %>
            </div>
            </div>
            <div class="yacht-detail-card  w-100 ">
               <% # <div class="yacht-detail-card-content"> %>
               <i class="fa-solid fa-user-astronaut"></i>
               <% # </div> %>
               <% # <div class="yacht-detail-card-content"> %>
               <p><%= @yacht.user.bio %></p>
               <% # </div> %>
            </div>
         </div>
         <div class="text-description">
            <br>
            <p class="text-start my-3 line-height-1.5">
              <strong>More about this yacht:</strong> <br>
              <span style="line-height: 1.5;"></p>
              <p class="text-start my-3 line-height-2"><%= @yacht.description %></span></p>
         </div>
         <br>
      </div>



      <div  class="d-flex align-items-start form" id="yacht-show" style="height: fit-content;">
         <%= simple_form_for [@yacht, @booking] do |f| %>
         <%= f.input :check_in,
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
         <%= f.input :check_out,
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
         <%= f.input :guests %>
         <%= f.submit "Book now", class: "btn btn-outline-info border-1"  %>
        <h4 class=" mt-5
         price mb-5">Price per night: <span style="margin-right: 50px;"></span> £<%= @yacht.price_per_night%>0</h4>
         <% end %>
      </div>

   </div>
      <div class="reviews">
       <div class="top-review-text">
          <h2>Reviews</h2>
          <%= link_to "Add a Review", new_yacht_review_path(@yacht), class: "btn btn-outline-info border-1" %>
        </div>
        <% @yacht.reviews.each do |review|%>
          <div class="review-card">
            <div><%= "⭐️"*review.rating %> -
            <%= review.user.first_name %> </div>
            <div><%= review.content %></div>
          </div>

        <% end %>
      </div>

</div>
  <div class="container">
    <h2 class="my-3">Where You'll Stay</h2>
      <div class="map-center mb-5" style="width: 100%; height: 400px; center-align text"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV["MAPBOX_API_KEY"] %>">
      </div>
    </div>

</div>